version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python3 manage.py makemigrations portal && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=records
      - DB_USER=testuser
      - DB_PASS=password
    depends_on:
      - db
    restart:
      "always"

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=records
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 2s
      timeout: 5s
      retries: 10
    volumes:
      - db-volume:/var/lib/postgresql/data

volumes:
  db-volume:
    